/*
 * generated by Xtext 2.9.2
 */
package org.xtext.project.stdc.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class StdcProposalProvider extends AbstractStdcProposalProvider {
}
