/*
 * generated by Xtext 2.9.2
 */
package org.xtext.project.stdc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StdcStandaloneSetup extends StdcStandaloneSetupGenerated {

	def static void doSetup() {
		new StdcStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
